//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.Tests.TestsBase;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of Luminosity.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class LuminosityTestsBase : QuantityTestsBase
    {
        protected abstract double DecawattsInOneWatt { get; }
        protected abstract double DeciwattsInOneWatt { get; }
        protected abstract double FemtowattsInOneWatt { get; }
        protected abstract double GigawattsInOneWatt { get; }
        protected abstract double KilowattsInOneWatt { get; }
        protected abstract double MegawattsInOneWatt { get; }
        protected abstract double MicrowattsInOneWatt { get; }
        protected abstract double MilliwattsInOneWatt { get; }
        protected abstract double NanowattsInOneWatt { get; }
        protected abstract double PetawattsInOneWatt { get; }
        protected abstract double PicowattsInOneWatt { get; }
        protected abstract double SolarLuminositiesInOneWatt { get; }
        protected abstract double TerawattsInOneWatt { get; }
        protected abstract double WattsInOneWatt { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double DecawattsTolerance { get { return 1e-5; } }
        protected virtual double DeciwattsTolerance { get { return 1e-5; } }
        protected virtual double FemtowattsTolerance { get { return 1e-5; } }
        protected virtual double GigawattsTolerance { get { return 1e-5; } }
        protected virtual double KilowattsTolerance { get { return 1e-5; } }
        protected virtual double MegawattsTolerance { get { return 1e-5; } }
        protected virtual double MicrowattsTolerance { get { return 1e-5; } }
        protected virtual double MilliwattsTolerance { get { return 1e-5; } }
        protected virtual double NanowattsTolerance { get { return 1e-5; } }
        protected virtual double PetawattsTolerance { get { return 1e-5; } }
        protected virtual double PicowattsTolerance { get { return 1e-5; } }
        protected virtual double SolarLuminositiesTolerance { get { return 1e-5; } }
        protected virtual double TerawattsTolerance { get { return 1e-5; } }
        protected virtual double WattsTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        protected (double UnitsInBaseUnit, double Tolerence) GetConversionFactor(LuminosityUnit unit)
        {
            return unit switch
            {
                LuminosityUnit.Decawatt => (DecawattsInOneWatt, DecawattsTolerance),
                LuminosityUnit.Deciwatt => (DeciwattsInOneWatt, DeciwattsTolerance),
                LuminosityUnit.Femtowatt => (FemtowattsInOneWatt, FemtowattsTolerance),
                LuminosityUnit.Gigawatt => (GigawattsInOneWatt, GigawattsTolerance),
                LuminosityUnit.Kilowatt => (KilowattsInOneWatt, KilowattsTolerance),
                LuminosityUnit.Megawatt => (MegawattsInOneWatt, MegawattsTolerance),
                LuminosityUnit.Microwatt => (MicrowattsInOneWatt, MicrowattsTolerance),
                LuminosityUnit.Milliwatt => (MilliwattsInOneWatt, MilliwattsTolerance),
                LuminosityUnit.Nanowatt => (NanowattsInOneWatt, NanowattsTolerance),
                LuminosityUnit.Petawatt => (PetawattsInOneWatt, PetawattsTolerance),
                LuminosityUnit.Picowatt => (PicowattsInOneWatt, PicowattsTolerance),
                LuminosityUnit.SolarLuminosity => (SolarLuminositiesInOneWatt, SolarLuminositiesTolerance),
                LuminosityUnit.Terawatt => (TerawattsInOneWatt, TerawattsTolerance),
                LuminosityUnit.Watt => (WattsInOneWatt, WattsTolerance),
                _ => throw new NotSupportedException()
            };
        }

        public static IEnumerable<object[]> UnitTypes = new List<object[]>
        {
            new object[] { LuminosityUnit.Decawatt },
            new object[] { LuminosityUnit.Deciwatt },
            new object[] { LuminosityUnit.Femtowatt },
            new object[] { LuminosityUnit.Gigawatt },
            new object[] { LuminosityUnit.Kilowatt },
            new object[] { LuminosityUnit.Megawatt },
            new object[] { LuminosityUnit.Microwatt },
            new object[] { LuminosityUnit.Milliwatt },
            new object[] { LuminosityUnit.Nanowatt },
            new object[] { LuminosityUnit.Petawatt },
            new object[] { LuminosityUnit.Picowatt },
            new object[] { LuminosityUnit.SolarLuminosity },
            new object[] { LuminosityUnit.Terawatt },
            new object[] { LuminosityUnit.Watt },
        };

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new Luminosity();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(LuminosityUnit.Watt, quantity.Unit);
        }

        [Fact]
        public void Ctor_WithInfinityValue_DoNotThrowsArgumentException()
        {
            var exception1 = Record.Exception(() => new Luminosity(double.PositiveInfinity, LuminosityUnit.Watt));
            var exception2 = Record.Exception(() => new Luminosity(double.NegativeInfinity, LuminosityUnit.Watt));

            Assert.Null(exception1);
            Assert.Null(exception2);
        }

        [Fact]
        public void Ctor_WithNaNValue_DoNotThrowsArgumentException()
        {
            var exception = Record.Exception(() => new Luminosity(double.NaN, LuminosityUnit.Watt));

            Assert.Null(exception);
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new Luminosity(value: 1, unitSystem: null));
        }

        [Fact]
        public void Ctor_SIUnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            if (SupportsSIUnitSystem)
            {
                var quantity = new Luminosity(value: 1, unitSystem: UnitSystem.SI);
                Assert.Equal(1, quantity.Value);
            }
            else
            {
                Assert.Throws<ArgumentException>(() => new Luminosity(value: 1, unitSystem: UnitSystem.SI));
            }
        }

        [Fact]
        public void Luminosity_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            var quantity = new Luminosity(1, LuminosityUnit.Watt);

            QuantityInfo<LuminosityUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal(Luminosity.Zero, quantityInfo.Zero);
            Assert.Equal("Luminosity", quantityInfo.Name);

            var units = EnumUtils.GetEnumValues<LuminosityUnit>().OrderBy(x => x.ToString()).ToArray();
            var unitNames = units.Select(x => x.ToString());
        }

        [Fact]
        public void WattToLuminosityUnits()
        {
            Luminosity watt = Luminosity.FromWatts(1);
            AssertEx.EqualTolerance(DecawattsInOneWatt, watt.Decawatts, DecawattsTolerance);
            AssertEx.EqualTolerance(DeciwattsInOneWatt, watt.Deciwatts, DeciwattsTolerance);
            AssertEx.EqualTolerance(FemtowattsInOneWatt, watt.Femtowatts, FemtowattsTolerance);
            AssertEx.EqualTolerance(GigawattsInOneWatt, watt.Gigawatts, GigawattsTolerance);
            AssertEx.EqualTolerance(KilowattsInOneWatt, watt.Kilowatts, KilowattsTolerance);
            AssertEx.EqualTolerance(MegawattsInOneWatt, watt.Megawatts, MegawattsTolerance);
            AssertEx.EqualTolerance(MicrowattsInOneWatt, watt.Microwatts, MicrowattsTolerance);
            AssertEx.EqualTolerance(MilliwattsInOneWatt, watt.Milliwatts, MilliwattsTolerance);
            AssertEx.EqualTolerance(NanowattsInOneWatt, watt.Nanowatts, NanowattsTolerance);
            AssertEx.EqualTolerance(PetawattsInOneWatt, watt.Petawatts, PetawattsTolerance);
            AssertEx.EqualTolerance(PicowattsInOneWatt, watt.Picowatts, PicowattsTolerance);
            AssertEx.EqualTolerance(SolarLuminositiesInOneWatt, watt.SolarLuminosities, SolarLuminositiesTolerance);
            AssertEx.EqualTolerance(TerawattsInOneWatt, watt.Terawatts, TerawattsTolerance);
            AssertEx.EqualTolerance(WattsInOneWatt, watt.Watts, WattsTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            var quantity00 = Luminosity.From(1, LuminosityUnit.Decawatt);
            Assert.Equal(1, quantity00.Decawatts);
            Assert.Equal(LuminosityUnit.Decawatt, quantity00.Unit);

            var quantity01 = Luminosity.From(1, LuminosityUnit.Deciwatt);
            Assert.Equal(1, quantity01.Deciwatts);
            Assert.Equal(LuminosityUnit.Deciwatt, quantity01.Unit);

            var quantity02 = Luminosity.From(1, LuminosityUnit.Femtowatt);
            Assert.Equal(1, quantity02.Femtowatts);
            Assert.Equal(LuminosityUnit.Femtowatt, quantity02.Unit);

            var quantity03 = Luminosity.From(1, LuminosityUnit.Gigawatt);
            Assert.Equal(1, quantity03.Gigawatts);
            Assert.Equal(LuminosityUnit.Gigawatt, quantity03.Unit);

            var quantity04 = Luminosity.From(1, LuminosityUnit.Kilowatt);
            Assert.Equal(1, quantity04.Kilowatts);
            Assert.Equal(LuminosityUnit.Kilowatt, quantity04.Unit);

            var quantity05 = Luminosity.From(1, LuminosityUnit.Megawatt);
            Assert.Equal(1, quantity05.Megawatts);
            Assert.Equal(LuminosityUnit.Megawatt, quantity05.Unit);

            var quantity06 = Luminosity.From(1, LuminosityUnit.Microwatt);
            Assert.Equal(1, quantity06.Microwatts);
            Assert.Equal(LuminosityUnit.Microwatt, quantity06.Unit);

            var quantity07 = Luminosity.From(1, LuminosityUnit.Milliwatt);
            Assert.Equal(1, quantity07.Milliwatts);
            Assert.Equal(LuminosityUnit.Milliwatt, quantity07.Unit);

            var quantity08 = Luminosity.From(1, LuminosityUnit.Nanowatt);
            Assert.Equal(1, quantity08.Nanowatts);
            Assert.Equal(LuminosityUnit.Nanowatt, quantity08.Unit);

            var quantity09 = Luminosity.From(1, LuminosityUnit.Petawatt);
            Assert.Equal(1, quantity09.Petawatts);
            Assert.Equal(LuminosityUnit.Petawatt, quantity09.Unit);

            var quantity10 = Luminosity.From(1, LuminosityUnit.Picowatt);
            Assert.Equal(1, quantity10.Picowatts);
            Assert.Equal(LuminosityUnit.Picowatt, quantity10.Unit);

            var quantity11 = Luminosity.From(1, LuminosityUnit.SolarLuminosity);
            Assert.Equal(1, quantity11.SolarLuminosities);
            Assert.Equal(LuminosityUnit.SolarLuminosity, quantity11.Unit);

            var quantity12 = Luminosity.From(1, LuminosityUnit.Terawatt);
            Assert.Equal(1, quantity12.Terawatts);
            Assert.Equal(LuminosityUnit.Terawatt, quantity12.Unit);

            var quantity13 = Luminosity.From(1, LuminosityUnit.Watt);
            Assert.Equal(1, quantity13.Watts);
            Assert.Equal(LuminosityUnit.Watt, quantity13.Unit);

        }

        [Fact]
        public void FromWatts_WithInfinityValue_DoNotThrowsArgumentException()
        {
            var exception1 = Record.Exception(() => Luminosity.FromWatts(double.PositiveInfinity));
            var exception2 = Record.Exception(() => Luminosity.FromWatts(double.NegativeInfinity));

            Assert.Null(exception1);
            Assert.Null(exception2);
        }

        [Fact]
        public void FromWatts_WithNanValue_DoNotThrowsArgumentException()
        {
            var exception = Record.Exception(() => Luminosity.FromWatts(double.NaN));

            Assert.Null(exception);
        }

        [Fact]
        public void As()
        {
            var watt = Luminosity.FromWatts(1);
            AssertEx.EqualTolerance(DecawattsInOneWatt, watt.As(LuminosityUnit.Decawatt), DecawattsTolerance);
            AssertEx.EqualTolerance(DeciwattsInOneWatt, watt.As(LuminosityUnit.Deciwatt), DeciwattsTolerance);
            AssertEx.EqualTolerance(FemtowattsInOneWatt, watt.As(LuminosityUnit.Femtowatt), FemtowattsTolerance);
            AssertEx.EqualTolerance(GigawattsInOneWatt, watt.As(LuminosityUnit.Gigawatt), GigawattsTolerance);
            AssertEx.EqualTolerance(KilowattsInOneWatt, watt.As(LuminosityUnit.Kilowatt), KilowattsTolerance);
            AssertEx.EqualTolerance(MegawattsInOneWatt, watt.As(LuminosityUnit.Megawatt), MegawattsTolerance);
            AssertEx.EqualTolerance(MicrowattsInOneWatt, watt.As(LuminosityUnit.Microwatt), MicrowattsTolerance);
            AssertEx.EqualTolerance(MilliwattsInOneWatt, watt.As(LuminosityUnit.Milliwatt), MilliwattsTolerance);
            AssertEx.EqualTolerance(NanowattsInOneWatt, watt.As(LuminosityUnit.Nanowatt), NanowattsTolerance);
            AssertEx.EqualTolerance(PetawattsInOneWatt, watt.As(LuminosityUnit.Petawatt), PetawattsTolerance);
            AssertEx.EqualTolerance(PicowattsInOneWatt, watt.As(LuminosityUnit.Picowatt), PicowattsTolerance);
            AssertEx.EqualTolerance(SolarLuminositiesInOneWatt, watt.As(LuminosityUnit.SolarLuminosity), SolarLuminositiesTolerance);
            AssertEx.EqualTolerance(TerawattsInOneWatt, watt.As(LuminosityUnit.Terawatt), TerawattsTolerance);
            AssertEx.EqualTolerance(WattsInOneWatt, watt.As(LuminosityUnit.Watt), WattsTolerance);
        }

        [Fact]
        public void As_SIUnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            var quantity = new Luminosity(value: 1, unit: Luminosity.BaseUnit);
            if (SupportsSIUnitSystem)
            {
                Assert.Equal(1, quantity.As(UnitSystem.SI));
            }
            else
            {
                Assert.Throws<ArgumentException>(() => quantity.As(UnitSystem.SI));
            }
        }

        [Fact]
        public void Parse()
        {
            try
            {
                var parsed = Luminosity.Parse("1 daW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Decawatts);
                Assert.Equal(LuminosityUnit.Decawatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 dW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Deciwatts);
                Assert.Equal(LuminosityUnit.Deciwatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 fW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Femtowatts);
                Assert.Equal(LuminosityUnit.Femtowatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 GW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Gigawatts);
                Assert.Equal(LuminosityUnit.Gigawatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 kW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Kilowatts);
                Assert.Equal(LuminosityUnit.Kilowatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 MW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Megawatts);
                Assert.Equal(LuminosityUnit.Megawatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 µW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Microwatts);
                Assert.Equal(LuminosityUnit.Microwatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 mW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Milliwatts);
                Assert.Equal(LuminosityUnit.Milliwatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 nW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Nanowatts);
                Assert.Equal(LuminosityUnit.Nanowatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 PW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Petawatts);
                Assert.Equal(LuminosityUnit.Petawatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 pW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Picowatts);
                Assert.Equal(LuminosityUnit.Picowatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 L⊙", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.SolarLuminosities);
                Assert.Equal(LuminosityUnit.SolarLuminosity, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 TW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Terawatts);
                Assert.Equal(LuminosityUnit.Terawatt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsed = Luminosity.Parse("1 W", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(1, parsed.Watts);
                Assert.Equal(LuminosityUnit.Watt, parsed.Unit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

        }

        [Fact]
        public void TryParse()
        {
            {
                Assert.True(Luminosity.TryParse("1 daW", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Decawatts);
                Assert.Equal(LuminosityUnit.Decawatt, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 dW", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Deciwatts);
                Assert.Equal(LuminosityUnit.Deciwatt, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 fW", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Femtowatts);
                Assert.Equal(LuminosityUnit.Femtowatt, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 GW", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Gigawatts);
                Assert.Equal(LuminosityUnit.Gigawatt, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 kW", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Kilowatts);
                Assert.Equal(LuminosityUnit.Kilowatt, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 µW", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Microwatts);
                Assert.Equal(LuminosityUnit.Microwatt, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 nW", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Nanowatts);
                Assert.Equal(LuminosityUnit.Nanowatt, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 L⊙", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.SolarLuminosities);
                Assert.Equal(LuminosityUnit.SolarLuminosity, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 TW", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Terawatts);
                Assert.Equal(LuminosityUnit.Terawatt, parsed.Unit);
            }

            {
                Assert.True(Luminosity.TryParse("1 W", CultureInfo.GetCultureInfo("en-US"), out var parsed));
                Assert.Equal(1, parsed.Watts);
                Assert.Equal(LuminosityUnit.Watt, parsed.Unit);
            }

        }

        [Fact]
        public void ParseUnit()
        {
            try
            {
                var parsedUnit = Luminosity.ParseUnit("daW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Decawatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("dW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Deciwatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("fW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Femtowatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("GW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Gigawatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("kW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Kilowatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("MW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Megawatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("µW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Microwatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("mW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Milliwatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("nW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Nanowatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("PW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Petawatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("pW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Picowatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("L⊙", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.SolarLuminosity, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("TW", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Terawatt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

            try
            {
                var parsedUnit = Luminosity.ParseUnit("W", CultureInfo.GetCultureInfo("en-US"));
                Assert.Equal(LuminosityUnit.Watt, parsedUnit);
            } catch (AmbiguousUnitParseException) { /* Some units have the same abbreviations */ }

        }

        [Fact]
        public void TryParseUnit()
        {
            {
                Assert.True(Luminosity.TryParseUnit("daW", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Decawatt, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("dW", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Deciwatt, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("fW", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Femtowatt, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("GW", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Gigawatt, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("kW", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Kilowatt, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("µW", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Microwatt, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("nW", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Nanowatt, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("L⊙", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.SolarLuminosity, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("TW", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Terawatt, parsedUnit);
            }

            {
                Assert.True(Luminosity.TryParseUnit("W", CultureInfo.GetCultureInfo("en-US"), out var parsedUnit));
                Assert.Equal(LuminosityUnit.Watt, parsedUnit);
            }

        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit(LuminosityUnit unit)
        {
            var inBaseUnits = Luminosity.From(1.0, Luminosity.BaseUnit);
            var converted = inBaseUnits.ToUnit(unit);

            var conversionFactor = GetConversionFactor(unit);
            AssertEx.EqualTolerance(conversionFactor.UnitsInBaseUnit, converted.Value, conversionFactor.Tolerence);
            Assert.Equal(unit, converted.Unit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit_WithSameUnits_AreEqual(LuminosityUnit unit)
        {
            var quantity = Luminosity.From(3.0, unit);
            var toUnitWithSameUnit = quantity.ToUnit(unit);
            Assert.Equal(quantity, toUnitWithSameUnit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit_FromNonBaseUnit_ReturnsQuantityWithGivenUnit(LuminosityUnit unit)
        {
            // See if there is a unit available that is not the base unit, fallback to base unit if it has only a single unit.
            var fromUnit = Luminosity.Units.First(u => u != Luminosity.BaseUnit);

            var quantity = Luminosity.From(3.0, fromUnit);
            var converted = quantity.ToUnit(unit);
            Assert.Equal(converted.Unit, unit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public virtual void ToUnit_FromDefaultQuantity_ReturnsQuantityWithGivenUnit(LuminosityUnit unit)
        {
            var quantity = default(Luminosity);
            var converted = quantity.ToUnit(unit);
            Assert.Equal(converted.Unit, unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            Luminosity watt = Luminosity.FromWatts(1);
            Assert.Equal(1, Luminosity.FromDecawatts(watt.Decawatts).Watts);
            Assert.Equal(1, Luminosity.FromDeciwatts(watt.Deciwatts).Watts);
            Assert.Equal(1, Luminosity.FromFemtowatts(watt.Femtowatts).Watts);
            Assert.Equal(1, Luminosity.FromGigawatts(watt.Gigawatts).Watts);
            Assert.Equal(1, Luminosity.FromKilowatts(watt.Kilowatts).Watts);
            Assert.Equal(1, Luminosity.FromMegawatts(watt.Megawatts).Watts);
            Assert.Equal(1, Luminosity.FromMicrowatts(watt.Microwatts).Watts);
            Assert.Equal(1, Luminosity.FromMilliwatts(watt.Milliwatts).Watts);
            Assert.Equal(1, Luminosity.FromNanowatts(watt.Nanowatts).Watts);
            Assert.Equal(1, Luminosity.FromPetawatts(watt.Petawatts).Watts);
            Assert.Equal(1, Luminosity.FromPicowatts(watt.Picowatts).Watts);
            Assert.Equal(1, Luminosity.FromSolarLuminosities(watt.SolarLuminosities).Watts);
            Assert.Equal(1, Luminosity.FromTerawatts(watt.Terawatts).Watts);
            Assert.Equal(1, Luminosity.FromWatts(watt.Watts).Watts);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            Luminosity v = Luminosity.FromWatts(1);
            Assert.Equal(-1, -v.Watts);
            Assert.Equal(2, (Luminosity.FromWatts(3) - v).Watts);
            Assert.Equal(2, (v + v).Watts);
            Assert.Equal(10, (v * 10).Watts);
            Assert.Equal(10, (10 * v).Watts);
            Assert.Equal(2, (Luminosity.FromWatts(10) / 5).Watts);
            Assert.Equal(2, Luminosity.FromWatts(10) / Luminosity.FromWatts(5));
        }

        [Fact]
        public void ComparisonOperators()
        {
            Luminosity oneWatt = Luminosity.FromWatts(1);
            Luminosity twoWatts = Luminosity.FromWatts(2);

            Assert.True(oneWatt < twoWatts);
            Assert.True(oneWatt <= twoWatts);
            Assert.True(twoWatts > oneWatt);
            Assert.True(twoWatts >= oneWatt);

            Assert.False(oneWatt > twoWatts);
            Assert.False(oneWatt >= twoWatts);
            Assert.False(twoWatts < oneWatt);
            Assert.False(twoWatts <= oneWatt);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            Luminosity watt = Luminosity.FromWatts(1);
            Assert.Equal(0, watt.CompareTo(watt));
            Assert.True(watt.CompareTo(Luminosity.Zero) > 0);
            Assert.True(Luminosity.Zero.CompareTo(watt) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            Luminosity watt = Luminosity.FromWatts(1);
            Assert.Throws<ArgumentException>(() => watt.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            Luminosity watt = Luminosity.FromWatts(1);
            Assert.Throws<ArgumentNullException>(() => watt.CompareTo(null));
        }

        [Theory]
        [InlineData(1, LuminosityUnit.Watt, 1, LuminosityUnit.Watt, true)]  // Same value and unit.
        [InlineData(1, LuminosityUnit.Watt, 2, LuminosityUnit.Watt, false)] // Different value.
        public void Equals_ReturnsTrue_IfValueAndUnitAreEqual(double valueA, LuminosityUnit unitA, double valueB, LuminosityUnit unitB, bool expectEqual)
        {
            var a = new Luminosity(valueA, unitA);
            var b = new Luminosity(valueB, unitB);

            // Operator overloads.
            Assert.Equal(expectEqual, a == b);
            Assert.Equal(expectEqual, b == a);
            Assert.Equal(!expectEqual, a != b);
            Assert.Equal(!expectEqual, b != a);

            // IEquatable<T>
            Assert.Equal(expectEqual, a.Equals(b));
            Assert.Equal(expectEqual, b.Equals(a));

            // IEquatable
            Assert.Equal(expectEqual, a.Equals((object)b));
            Assert.Equal(expectEqual, b.Equals((object)a));
        }

        [Fact]
        public void Equals_Null_ReturnsFalse()
        {
            var a = Luminosity.Zero;

            Assert.False(a.Equals((object)null));

            // "The result of the expression is always 'false'..."
            #pragma warning disable CS8073
            Assert.False(a == null);
            Assert.False(null == a);
            Assert.True(a != null);
            Assert.True(null != a);
            #pragma warning restore CS8073
        }

        [Fact]
        public void Equals_WithTolerance_IsImplemented()
        {
            var v = Luminosity.FromWatts(1);
            Assert.True(v.Equals(Luminosity.FromWatts(1), Luminosity.FromWatts(0)));
            Assert.True(v.Equals(Luminosity.FromWatts(1), Luminosity.FromWatts(0.001m)));
            Assert.True(v.Equals(Luminosity.FromWatts(0.9999), Luminosity.FromWatts(0.001m)));
            Assert.False(v.Equals(Luminosity.FromWatts(0.99), Luminosity.FromWatts(0.001m)));
            Assert.False(v.Equals(Luminosity.Zero, Luminosity.FromWatts(0.001m)));
        }

        [Fact]
        public void Equals_WithNegativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var v = Luminosity.FromWatts(1);
            var negativeTolerance = Luminosity.FromWatts(-1);
            Assert.Throws<ArgumentOutOfRangeException>(() => v.Equals(Luminosity.FromWatts(1), negativeTolerance));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            Luminosity watt = Luminosity.FromWatts(1);
            Assert.False(watt.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            Luminosity watt = Luminosity.FromWatts(1);
            Assert.False(watt.Equals(null));
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = Enum.GetValues(typeof(LuminosityUnit)).Cast<LuminosityUnit>();
            foreach (var unit in units)
            {
                var defaultAbbreviation = UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(Luminosity.BaseDimensions is null);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            var prevCulture = Thread.CurrentThread.CurrentCulture;
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US");
            try {
                Assert.Equal("1 daW", new Luminosity(1, LuminosityUnit.Decawatt).ToString());
                Assert.Equal("1 dW", new Luminosity(1, LuminosityUnit.Deciwatt).ToString());
                Assert.Equal("1 fW", new Luminosity(1, LuminosityUnit.Femtowatt).ToString());
                Assert.Equal("1 GW", new Luminosity(1, LuminosityUnit.Gigawatt).ToString());
                Assert.Equal("1 kW", new Luminosity(1, LuminosityUnit.Kilowatt).ToString());
                Assert.Equal("1 MW", new Luminosity(1, LuminosityUnit.Megawatt).ToString());
                Assert.Equal("1 µW", new Luminosity(1, LuminosityUnit.Microwatt).ToString());
                Assert.Equal("1 mW", new Luminosity(1, LuminosityUnit.Milliwatt).ToString());
                Assert.Equal("1 nW", new Luminosity(1, LuminosityUnit.Nanowatt).ToString());
                Assert.Equal("1 PW", new Luminosity(1, LuminosityUnit.Petawatt).ToString());
                Assert.Equal("1 pW", new Luminosity(1, LuminosityUnit.Picowatt).ToString());
                Assert.Equal("1 L⊙", new Luminosity(1, LuminosityUnit.SolarLuminosity).ToString());
                Assert.Equal("1 TW", new Luminosity(1, LuminosityUnit.Terawatt).ToString());
                Assert.Equal("1 W", new Luminosity(1, LuminosityUnit.Watt).ToString());
            }
            finally
            {
                Thread.CurrentThread.CurrentCulture = prevCulture;
            }
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 daW", new Luminosity(1, LuminosityUnit.Decawatt).ToString(swedishCulture));
            Assert.Equal("1 dW", new Luminosity(1, LuminosityUnit.Deciwatt).ToString(swedishCulture));
            Assert.Equal("1 fW", new Luminosity(1, LuminosityUnit.Femtowatt).ToString(swedishCulture));
            Assert.Equal("1 GW", new Luminosity(1, LuminosityUnit.Gigawatt).ToString(swedishCulture));
            Assert.Equal("1 kW", new Luminosity(1, LuminosityUnit.Kilowatt).ToString(swedishCulture));
            Assert.Equal("1 MW", new Luminosity(1, LuminosityUnit.Megawatt).ToString(swedishCulture));
            Assert.Equal("1 µW", new Luminosity(1, LuminosityUnit.Microwatt).ToString(swedishCulture));
            Assert.Equal("1 mW", new Luminosity(1, LuminosityUnit.Milliwatt).ToString(swedishCulture));
            Assert.Equal("1 nW", new Luminosity(1, LuminosityUnit.Nanowatt).ToString(swedishCulture));
            Assert.Equal("1 PW", new Luminosity(1, LuminosityUnit.Petawatt).ToString(swedishCulture));
            Assert.Equal("1 pW", new Luminosity(1, LuminosityUnit.Picowatt).ToString(swedishCulture));
            Assert.Equal("1 L⊙", new Luminosity(1, LuminosityUnit.SolarLuminosity).ToString(swedishCulture));
            Assert.Equal("1 TW", new Luminosity(1, LuminosityUnit.Terawatt).ToString(swedishCulture));
            Assert.Equal("1 W", new Luminosity(1, LuminosityUnit.Watt).ToString(swedishCulture));
        }

        [Fact]
        public void ToString_SFormat_FormatsNumberWithGivenDigitsAfterRadixForCurrentCulture()
        {
            var oldCulture = CultureInfo.CurrentCulture;
            try
            {
                CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
                Assert.Equal("0.1 W", new Luminosity(0.123456, LuminosityUnit.Watt).ToString("s1"));
                Assert.Equal("0.12 W", new Luminosity(0.123456, LuminosityUnit.Watt).ToString("s2"));
                Assert.Equal("0.123 W", new Luminosity(0.123456, LuminosityUnit.Watt).ToString("s3"));
                Assert.Equal("0.1235 W", new Luminosity(0.123456, LuminosityUnit.Watt).ToString("s4"));
            }
            finally
            {
                CultureInfo.CurrentCulture = oldCulture;
            }
        }

        [Fact]
        public void ToString_SFormatAndCulture_FormatsNumberWithGivenDigitsAfterRadixForGivenCulture()
        {
            var culture = CultureInfo.InvariantCulture;
            Assert.Equal("0.1 W", new Luminosity(0.123456, LuminosityUnit.Watt).ToString("s1", culture));
            Assert.Equal("0.12 W", new Luminosity(0.123456, LuminosityUnit.Watt).ToString("s2", culture));
            Assert.Equal("0.123 W", new Luminosity(0.123456, LuminosityUnit.Watt).ToString("s3", culture));
            Assert.Equal("0.1235 W", new Luminosity(0.123456, LuminosityUnit.Watt).ToString("s4", culture));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("en-US")]
        public void ToString_NullFormat_DefaultsToGeneralFormat(string cultureName)
        {
            var quantity = Luminosity.FromWatts(1.0);
            CultureInfo formatProvider = cultureName == null
                ? null
                : CultureInfo.GetCultureInfo(cultureName);

            Assert.Equal(quantity.ToString("g", formatProvider), quantity.ToString(null, formatProvider));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("g")]
        public void ToString_NullProvider_EqualsCurrentCulture(string format)
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal(quantity.ToString(format, CultureInfo.CurrentCulture), quantity.ToString(format, null));
        }

        [Fact]
        public void Convert_ToBool_ThrowsInvalidCastException()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToBoolean(quantity));
        }

        [Fact]
        public void Convert_ToByte_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
           Assert.Equal((byte)quantity.Value, Convert.ToByte(quantity));
        }

        [Fact]
        public void Convert_ToChar_ThrowsInvalidCastException()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToChar(quantity));
        }

        [Fact]
        public void Convert_ToDateTime_ThrowsInvalidCastException()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ToDateTime(quantity));
        }

        [Fact]
        public void Convert_ToDecimal_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((decimal)quantity.Value, Convert.ToDecimal(quantity));
        }

        [Fact]
        public void Convert_ToDouble_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((double)quantity.Value, Convert.ToDouble(quantity));
        }

        [Fact]
        public void Convert_ToInt16_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((short)quantity.Value, Convert.ToInt16(quantity));
        }

        [Fact]
        public void Convert_ToInt32_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((int)quantity.Value, Convert.ToInt32(quantity));
        }

        [Fact]
        public void Convert_ToInt64_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((long)quantity.Value, Convert.ToInt64(quantity));
        }

        [Fact]
        public void Convert_ToSByte_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((sbyte)quantity.Value, Convert.ToSByte(quantity));
        }

        [Fact]
        public void Convert_ToSingle_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((float)quantity.Value, Convert.ToSingle(quantity));
        }

        [Fact]
        public void Convert_ToString_EqualsToString()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal(quantity.ToString(), Convert.ToString(quantity));
        }

        [Fact]
        public void Convert_ToUInt16_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((ushort)quantity.Value, Convert.ToUInt16(quantity));
        }

        [Fact]
        public void Convert_ToUInt32_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((uint)quantity.Value, Convert.ToUInt32(quantity));
        }

        [Fact]
        public void Convert_ToUInt64_EqualsValueAsSameType()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal((ulong)quantity.Value, Convert.ToUInt64(quantity));
        }

        [Fact]
        public void Convert_ChangeType_SelfType_EqualsSelf()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal(quantity, Convert.ChangeType(quantity, typeof(Luminosity)));
        }

        [Fact]
        public void Convert_ChangeType_UnitType_EqualsUnit()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal(quantity.Unit, Convert.ChangeType(quantity, typeof(LuminosityUnit)));
        }

        [Fact]
        public void Convert_ChangeType_QuantityInfo_EqualsQuantityInfo()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal(Luminosity.Info, Convert.ChangeType(quantity, typeof(QuantityInfo)));
        }

        [Fact]
        public void Convert_ChangeType_BaseDimensions_EqualsBaseDimensions()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Equal(Luminosity.BaseDimensions, Convert.ChangeType(quantity, typeof(BaseDimensions)));
        }

        [Fact]
        public void Convert_ChangeType_InvalidType_ThrowsInvalidCastException()
        {
            var quantity = Luminosity.FromWatts(1.0);
            Assert.Throws<InvalidCastException>(() => Convert.ChangeType(quantity, typeof(QuantityFormatter)));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = Luminosity.FromWatts(1.0);
            #if NET7_0_OR_GREATER
            var expected = HashCode.Combine(Luminosity.Info.Name, quantity.Watts);
            #else
            var expected = new {Luminosity.Info.Name, valueInBaseUnit = quantity.Watts}.GetHashCode();
            #endif
            Assert.Equal(expected, quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = Luminosity.FromWatts(value);
            Assert.Equal(Luminosity.FromWatts(-value), -quantity);
        }
    }
}
