//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.UnitSystems
{

    public partial class CGS
    {
        /// <summary>
        /// Returns the list of unit mappings for the current unit system
        /// </summary>
        /// <returns>The list of unit system infos</returns>
        public static UnitSystemInfo[] GetDefaultSystemUnits()
        {
            return new UnitSystemInfo[]
            {
                new UnitSystemInfo(Acceleration.Info.UnitInfos[0], new UnitInfo[]{
                    Acceleration.Info.UnitInfos[0],
                    Acceleration.Info.UnitInfos[1],
                    Acceleration.Info.UnitInfos[4],
                    Acceleration.Info.UnitInfos[8],
                    Acceleration.Info.UnitInfos[9],
                    Acceleration.Info.UnitInfos[10],
                    Acceleration.Info.UnitInfos[11],
                    }),
                new UnitSystemInfo(AmountOfSubstance.Info.UnitInfos[11], new UnitInfo[]{
                    AmountOfSubstance.Info.UnitInfos[0],
                    AmountOfSubstance.Info.UnitInfos[2],
                    AmountOfSubstance.Info.UnitInfos[4],
                    AmountOfSubstance.Info.UnitInfos[6],
                    AmountOfSubstance.Info.UnitInfos[7],
                    AmountOfSubstance.Info.UnitInfos[9],
                    AmountOfSubstance.Info.UnitInfos[11],
                    AmountOfSubstance.Info.UnitInfos[12],
                    }),
                null,
                null,
                null,
                null,
                new UnitSystemInfo(Area.Info.UnitInfos[2], new UnitInfo[]{
                    Area.Info.UnitInfos[1],
                    Area.Info.UnitInfos[2],
                    Area.Info.UnitInfos[3],
                    Area.Info.UnitInfos[6],
                    Area.Info.UnitInfos[7],
                    Area.Info.UnitInfos[8],
                    Area.Info.UnitInfos[10],
                    }),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                new UnitSystemInfo(Energy.Info.UnitInfos[6], new UnitInfo[]{
                    Energy.Info.UnitInfos[1],
                    Energy.Info.UnitInfos[6],
                    Energy.Info.UnitInfos[10],
                    Energy.Info.UnitInfos[12],
                    Energy.Info.UnitInfos[13],
                    Energy.Info.UnitInfos[16],
                    Energy.Info.UnitInfos[18],
                    }),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                new UnitSystemInfo(Length.Info.UnitInfos[1], new UnitInfo[]{
                    Length.Info.UnitInfos[1],
                    Length.Info.UnitInfos[2],
                    Length.Info.UnitInfos[8],
                    Length.Info.UnitInfos[11],
                    Length.Info.UnitInfos[16],
                    Length.Info.UnitInfos[18],
                    Length.Info.UnitInfos[21],
                    Length.Info.UnitInfos[22],
                    }),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                new UnitSystemInfo(Volume.Info.UnitInfos[3], new UnitInfo[]{
                    Volume.Info.UnitInfos[2],
                    Volume.Info.UnitInfos[3],
                    Volume.Info.UnitInfos[4],
                    Volume.Info.UnitInfos[6],
                    Volume.Info.UnitInfos[8],
                    Volume.Info.UnitInfos[9],
                    Volume.Info.UnitInfos[10],
                    Volume.Info.UnitInfos[12],
                    Volume.Info.UnitInfos[14],
                    Volume.Info.UnitInfos[16],
                    Volume.Info.UnitInfos[17],
                    Volume.Info.UnitInfos[23],
                    Volume.Info.UnitInfos[25],
                    Volume.Info.UnitInfos[27],
                    Volume.Info.UnitInfos[30],
                    Volume.Info.UnitInfos[34],
                    Volume.Info.UnitInfos[35],
                    }),
                null,
                null,
                null,
            };
        }
    }
}

